USE TestQuranFarsh

INSERT INTO Chapters (Id, Name) VALUES (1, 'الفاتحة')
INSERT INTO Chapters (Id, Name) VALUES (2, 'البقرة')
INSERT INTO Chapters (Id, Name) VALUES (3, 'آل عمران')
INSERT INTO Chapters (Id, Name) VALUES (4, 'النساء')
INSERT INTO Chapters (Id, Name) VALUES (5, 'المائدة')
INSERT INTO Chapters (Id, Name) VALUES (6, 'الأنعام')
INSERT INTO Chapters (Id, Name) VALUES (7, 'الأعراف')
INSERT INTO Chapters (Id, Name) VALUES (8, 'الأنفال')
INSERT INTO Chapters (Id, Name) VALUES (9, 'التوبة')

INSERT INTO Readers (Id, Name, ParentId) VALUES (1, 'نافع', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (2, 'قالون', 1)
INSERT INTO Readers (Id, Name, ParentId) VALUES (3, 'ورش', 1)
INSERT INTO Readers (Id, Name, ParentId) VALUES (4, 'ابن كثير', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (5, 'البزي', 4)
INSERT INTO Readers (Id, Name, ParentId) VALUES (6, 'قنبل', 4)
INSERT INTO Readers (Id, Name, ParentId) VALUES (7, 'أبو عمرو', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (8, 'الدوري عن أبي عمرو', 7)
INSERT INTO Readers (Id, Name, ParentId) VALUES (9, 'السوسي', 7)
INSERT INTO Readers (Id, Name, ParentId) VALUES (10, 'ابن عامر', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (11, 'هشام', 10)
INSERT INTO Readers (Id, Name, ParentId) VALUES (12, 'ابن ذكوان', 10)
INSERT INTO Readers (Id, Name, ParentId) VALUES (13, 'عاصم', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (14, 'شعبة', 13)
INSERT INTO Readers (Id, Name, ParentId) VALUES (15, 'حفص', 13)
INSERT INTO Readers (Id, Name, ParentId) VALUES (16, 'حمزة', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (17, 'خلف عن حمزة', 16)
INSERT INTO Readers (Id, Name, ParentId) VALUES (18, 'خلاد', 16)
INSERT INTO Readers (Id, Name, ParentId) VALUES (19, 'الكسائي', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (20, 'أبو الحارث', 19)
INSERT INTO Readers (Id, Name, ParentId) VALUES (21, 'الدوري عن الكسائي', 19)
INSERT INTO Readers (Id, Name, ParentId) VALUES (22, 'أبو جعفر', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (23, 'ابن وردان', 22)
INSERT INTO Readers (Id, Name, ParentId) VALUES (24, 'ابن جماز', 22)
INSERT INTO Readers (Id, Name, ParentId) VALUES (25, 'يعقوب', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (26, 'رويس', 25)
INSERT INTO Readers (Id, Name, ParentId) VALUES (27, 'روح', 25)
INSERT INTO Readers (Id, Name, ParentId) VALUES (28, 'خلف', NULL)
INSERT INTO Readers (Id, Name, ParentId) VALUES (29, 'إسحاق', 28)
INSERT INTO Readers (Id, Name, ParentId) VALUES (30, 'إدريس', 28)
